# Generated by Django 4.2.29 on 2026-04-25 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_agent_agentprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about_me',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='clarifying_questions',
            field=models.CharField(blank=True, choices=[('when_needed', 'When needed'), ('always', 'Always confirm'), ('never', 'Never ask, just go')], max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='communication_style',
            field=models.CharField(blank=True, choices=[('direct', 'Direct'), ('friendly', 'Friendly'), ('formal', 'Formal'), ('casual', 'Casual')], max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_size',
            field=models.CharField(blank=True, choices=[('solo', 'Solo'), ('2-10', '2–10'), ('11-50', '11–50'), ('51-200', '51–200'), ('200+', '200+')], max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_focus',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='customuser',
            name='emoji_use',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('sparingly', 'Sparingly'), ('freely', 'Freely')], max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='expertise_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='expertise_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='explanation_style',
            field=models.CharField(blank=True, choices=[('answer_only', 'Just give the answer'), ('with_reasoning', 'Explain reasoning'), ('step_by_step', 'Step by step')], max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='formality',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pushback_style',
            field=models.CharField(blank=True, choices=[('always', "Always tell me when I'm wrong"), ('diplomatic', 'Be diplomatic'), ('supportive', 'Supportive — acknowledge effort before critiquing')], max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='response_length',
            field=models.CharField(blank=True, choices=[('concise', 'Concise'), ('balanced', 'Balanced'), ('detailed', 'Detailed')], max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customuser',
            name='things_to_avoid',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='customuser',
            name='years_experience',
            field=models.CharField(blank=True, choices=[('<1', '<1'), ('1-3', '1–3'), ('3-7', '3–7'), ('7-15', '7–15'), ('15+', '15+')], max_length=10),
        ),
    ]
