# Generated by Django 4.2.29 on 2026-04-25 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_customuser_personalization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(help_text='URL-safe identifier; the application uses slugify() at create time.', max_length=80, unique=True)),
                ('icon_class', models.CharField(default='fa-briefcase', help_text="Font Awesome class (e.g. 'fa-house', 'fa-scale-balanced').", max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=100, help_text='Lower numbers appear first in lists.')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-disable without deletion.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='fa-toolbox', help_text="Font Awesome class (e.g. 'fa-toolbox').", max_length=80)),
                ('external_url', models.URLField(max_length=500)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='Soft-disable account without deletion.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_active_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Updated on each chat send for fast DAU/WAU queries.', null=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('event_date', models.DateTimeField(db_index=True, help_text="When the event occurs (indexed to support 'upcoming' filters).")),
                ('location', models.CharField(blank=True, max_length=200)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('registration_url', models.URLField(blank=True, max_length=500)),
                ('is_featured', models.BooleanField(default=False, help_text='Surface this event in featured banners and tile sections.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='myApp.industry')),
            ],
            options={
                'ordering': ['sort_order', 'event_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(db_index=True, help_text="Short category, e.g. 'openai_chat_send'.", max_length=80)),
                ('message', models.CharField(help_text='Truncated error message. Full stack traces stay in logger output.', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to='myApp.customuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(db_index=True, help_text="Dotted notation, e.g. 'user.suspend' or 'agent.delete'.", max_length=80)),
                ('target_type', models.CharField(blank=True, db_index=True, help_text="Resource type the action affected, e.g. 'user', 'agent'.", max_length=40)),
                ('target_id', models.PositiveIntegerField(blank=True, help_text='ID of the affected resource (nullable for actions without a single target).', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary JSON snapshot of the action payload or before/after state.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin', models.ForeignKey(help_text='The admin who performed the action.', on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to='myApp.customuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('banner_type', models.CharField(choices=[('info', 'Info'), ('warn', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_dismissible', models.BooleanField(default=True, help_text='If false, banner stays until end_at or admin deactivates.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners_created', to='myApp.customuser')),
            ],
            options={
                'ordering': ['-start_at'],
                'indexes': [models.Index(fields=['is_active', 'start_at', 'end_at'], name='banner_active_window_idx')],
            },
        ),
    ]
