# Generated by Django 4.2.29 on 2026-04-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_admin_dashboard_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, default='', help_text="e.g. 'Workshop', 'Webinar', 'Summit', 'Masterclass'. Free-form.", max_length=50),
        ),
    ]
