# Generated by Django 4.2.29 on 2026-04-28 11:22

from django.db import migrations, models


def backfill_existing_users(apps, schema_editor):
    """Mark every pre-existing user as verified + onboarded.

    Ensures the auth gate and onboarding flow do not lock out anyone who
    signed up before this phase shipped. Also resets onboarding_industry
    and onboarding_use_cases to defaults to avoid carrying stale state.
    """
    CustomUser = apps.get_model("myApp", "CustomUser")
    CustomUser.objects.all().update(
        email_verified=True,
        onboarding_completed=True,
        onboarding_industry="",
        onboarding_use_cases=list(),
    )


def noop_reverse(apps, schema_editor):
    """Reverse is a no-op — Django drops the columns on rollback."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_add_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verification_token',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_lifecycle_email_kind',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_lifecycle_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='onboarding_industry',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='customuser',
            name='onboarding_use_cases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(backfill_existing_users, noop_reverse),
    ]
