from django.urls import path, re_path
from django.views.generic import RedirectView

from . import views

legacy_redirect = lambda target: RedirectView.as_view(  # noqa: E731
    url=target, permanent=False, query_string=True
)

urlpatterns = [
    path("", views.home, name="home"),
    path("index/", views.home, name="index"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("agents/", views.agents, name="agents"),
    path("agent-chat/", views.agent_chat, name="agent_chat"),
    path("prompts/", views.prompts, name="prompts"),
    path("industries/", views.industries, name="industries"),
    path("events/", views.events, name="events"),
    path("tools/", views.tools, name="tools"),
    path("consulting/", views.consulting, name="consulting"),
    path("billing/", views.billing, name="billing"),
    path("profile/", views.profile_page, name="profile"),
    path("settings/", views.settings_page, name="settings"),
    path("login/", views.login, name="login"),
    path("register/", views.register, name="register"),
    path("verify-email-required/", views.verify_email_required, name="verify_email_required"),
    path("verify-email/", views.verify_email_page, name="verify_email"),
    path("onboarding/", views.onboarding_page, name="onboarding"),
    path("admin-dashboard/", views.admin_dashboard, name="admin_dashboard"),
    path("admin-dashboard/pulse/", views.admin_dashboard, name="admin_dashboard_pulse"),
    path("admin-dashboard/users/", views.admin_dashboard, name="admin_dashboard_users"),
    path("admin-dashboard/users/<int:user_id>/", views.admin_dashboard, name="admin_dashboard_user_detail"),
    path("admin-dashboard/content/", views.admin_dashboard, name="admin_dashboard_content"),
    path("admin-dashboard/content/agents/", views.admin_dashboard, name="admin_dashboard_agents"),
    path("admin-dashboard/content/agents/new/", views.admin_dashboard, name="admin_dashboard_agent_new"),
    path("admin-dashboard/content/agents/<int:agent_id>/", views.admin_dashboard, name="admin_dashboard_agent_edit"),
    path("admin-dashboard/content/prompts/", views.admin_dashboard, name="admin_dashboard_prompts"),
    path("admin-dashboard/content/prompts/new/", views.admin_dashboard, name="admin_dashboard_prompt_new"),
    path("admin-dashboard/content/prompts/<int:prompt_id>/", views.admin_dashboard, name="admin_dashboard_prompt_edit"),
    path("admin-dashboard/content/industries/", views.admin_dashboard, name="admin_dashboard_industries"),
    path("admin-dashboard/content/industries/new/", views.admin_dashboard, name="admin_dashboard_industry_new"),
    path("admin-dashboard/content/industries/<int:industry_id>/", views.admin_dashboard, name="admin_dashboard_industry_edit"),
    path("admin-dashboard/content/events/", views.admin_dashboard, name="admin_dashboard_events"),
    path("admin-dashboard/content/events/new/", views.admin_dashboard, name="admin_dashboard_event_new"),
    path("admin-dashboard/content/events/<int:event_id>/", views.admin_dashboard, name="admin_dashboard_event_edit"),
    path("admin-dashboard/content/tools/", views.admin_dashboard, name="admin_dashboard_tools"),
    path("admin-dashboard/content/tools/new/", views.admin_dashboard, name="admin_dashboard_tool_new"),
    path("admin-dashboard/content/tools/<int:tool_id>/", views.admin_dashboard, name="admin_dashboard_tool_edit"),
    path("admin-dashboard/content/banners/", views.admin_dashboard, name="admin_dashboard_banners"),
    path("admin-dashboard/content/banners/new/", views.admin_dashboard, name="admin_dashboard_banner_new"),
    path("admin-dashboard/content/banners/<int:banner_id>/", views.admin_dashboard, name="admin_dashboard_banner_edit"),
    path("admin-dashboard/operations/", views.admin_dashboard, name="admin_dashboard_operations"),
    path("admin-dashboard/operations/errors/", views.admin_dashboard, name="admin_dashboard_errors"),
    path("admin-dashboard/operations/audit/", views.admin_dashboard, name="admin_dashboard_audit"),
    path("admin-dashboard/operations/tokens/", views.admin_dashboard, name="admin_dashboard_tokens"),
    path("index.html", legacy_redirect("/index/"), name="legacy_index_html"),
    path("dashboard.html", legacy_redirect("/dashboard/"), name="legacy_dashboard_html"),
    path("agents.html", legacy_redirect("/agents/"), name="legacy_agents_html"),
    path("agent-chat.html", legacy_redirect("/agent-chat/"), name="legacy_agent_chat_html"),
    path("prompts.html", legacy_redirect("/prompts/"), name="legacy_prompts_html"),
    path("industries.html", legacy_redirect("/industries/"), name="legacy_industries_html"),
    path("events.html", legacy_redirect("/events/"), name="legacy_events_html"),
    path("tools.html", legacy_redirect("/tools/"), name="legacy_tools_html"),
    path("consulting.html", legacy_redirect("/consulting/"), name="legacy_consulting_html"),
    path("billing.html", legacy_redirect("/billing/"), name="legacy_billing_html"),
    path("profile.html", legacy_redirect("/profile/"), name="legacy_profile_html"),
    path("settings.html", legacy_redirect("/settings/"), name="legacy_settings_html"),
    path("login.html", legacy_redirect("/login/"), name="legacy_login_html"),
    path("register.html", legacy_redirect("/register/"), name="legacy_register_html"),
    path("verify-email-required.html", legacy_redirect("/verify-email-required/"), name="legacy_verify_email_required_html"),
    path("verify-email.html", legacy_redirect("/verify-email/"), name="legacy_verify_email_html"),
    path("onboarding.html", legacy_redirect("/onboarding/"), name="legacy_onboarding_html"),
    path("prompt-import.html", legacy_redirect("/prompt-import/"), name="legacy_prompt_import_html"),
    path("admin-dashboard.html", legacy_redirect("/admin-dashboard/"), name="legacy_admin_dashboard_html"),
    re_path(
        r"^(?:.*/)?(?P<page>(index|dashboard|agents|agent-chat|prompts|industries|events|tools|consulting|billing|profile|settings|login|register|verify-email-required|verify-email|onboarding|prompt-import)\.html)$",
        views.legacy_html_redirect,
        name="legacy_nested_html_redirect",
    ),
    path(
        "courses.html",
        RedirectView.as_view(url="https://courseforge.katek-ai.com/", permanent=False),
        name="courses_redirect_html",
    ),
    path(
        "courses/",
        RedirectView.as_view(url="https://courseforge.katek-ai.com/", permanent=False),
        name="courses_redirect",
    ),
    path("prompt-import/", views.prompt_import_dashboard, name="prompt_import_dashboard"),
    path("shared.css", views.shared_css, name="shared_css"),
    path("api/auth/register", views.api_register, name="api_register"),
    path("api/auth/login", views.api_login, name="api_login"),
    path("api/auth/logout", views.api_logout, name="api_logout"),
    path("api/auth/me", views.api_me, name="api_me"),
    path("api/auth/verify-email", views.api_verify_email, name="api_verify_email"),
    path("api/auth/resend-verification", views.api_resend_verification, name="api_resend_verification"),
    path("api/onboarding/state", views.api_onboarding_state, name="api_onboarding_state"),
    path("api/onboarding/complete", views.api_onboarding_complete, name="api_onboarding_complete"),
    path("api/profile", views.api_profile, name="api_profile"),
    path("api/dashboard", views.api_dashboard, name="api_dashboard"),
    path("api/agents", views.api_agents, name="api_agents"),
    path("api/industries", views.api_industries, name="api_industries"),
    path("api/prompts", views.api_prompts, name="api_prompts"),
    path("api/prompts/submit", views.api_submit_prompt, name="api_submit_prompt"),
    path("api/prompts/<int:prompt_id>/save", views.api_toggle_save_prompt, name="api_toggle_save_prompt"),
    path("api/chat/sessions", views.api_chat_sessions, name="api_chat_sessions"),
    path("api/chat/sessions/create", views.api_create_chat_session, name="api_create_chat_session"),
    path("api/chat/sessions/<int:session_id>/messages", views.api_chat_messages, name="api_chat_messages"),
    path("api/chat/upload-file", views.api_chat_upload_file, name="api_chat_upload_file"),
    path("api/chat/sessions/<int:session_id>/send", views.api_send_chat_message, name="api_send_chat_message"),
    path("api/chat/messages/<int:message_id>/feedback", views.api_message_feedback, name="api_message_feedback"),
    path("api/admin/pulse", views.api_pulse, name="api_admin_pulse"),
    path("api/admin/agents", views.api_admin_agents, name="api_admin_agents"),
    path("api/admin/agents/generate", views.api_admin_agent_generate, name="api_admin_agent_generate"),
    path("api/admin/agents/<int:agent_id>", views.api_admin_agent_detail, name="api_admin_agent_detail"),
    path(
        "api/admin/agents/<int:agent_id>/regenerate-avatar",
        views.api_admin_agent_regenerate_avatar,
        name="api_admin_agent_regenerate_avatar",
    ),
    path(
        "api/admin/agents/<int:agent_id>/prompts",
        views.api_admin_agent_prompts,
        name="api_admin_agent_prompts",
    ),
    path(
        "api/admin/agents/prompts/<int:prompt_id>",
        views.api_admin_agent_prompt_detail,
        name="api_admin_agent_prompt_detail",
    ),
    path("api/admin/prompts/import", views.api_admin_import_prompts, name="api_admin_import_prompts"),
    path("api/admin/prompts/categories", views.api_admin_prompts_categories, name="api_admin_prompts_categories"),
    path("api/admin/prompts", views.api_admin_prompts, name="api_admin_prompts"),
    path("api/admin/prompts/<int:prompt_id>", views.api_admin_prompt_detail, name="api_admin_prompt_detail"),
    path("api/admin/industries", views.api_admin_industries, name="api_admin_industries"),
    path("api/admin/industries/<int:industry_id>", views.api_admin_industry_detail, name="api_admin_industry_detail"),
    path("api/admin/users", views.api_admin_users, name="api_admin_users"),
    path("api/admin/users/export", views.api_admin_users_export, name="api_admin_users_export"),
    path("api/admin/users/<int:user_id>", views.api_admin_user_detail, name="api_admin_user_detail"),
    path("api/admin/users/<int:user_id>/suspend", views.api_admin_user_suspend, name="api_admin_user_suspend"),
    path("api/admin/users/<int:user_id>/unsuspend", views.api_admin_user_unsuspend, name="api_admin_user_unsuspend"),
    path("api/admin/users/<int:user_id>/impersonate", views.api_admin_user_impersonate, name="api_admin_user_impersonate"),
    path("api/admin/stop-impersonation", views.api_admin_stop_impersonation, name="api_admin_stop_impersonation"),
    path("api/admin/ops/summary", views.api_admin_ops_summary, name="api_admin_ops_summary"),
    path("api/admin/ops/token-usage", views.api_admin_ops_token_usage, name="api_admin_ops_token_usage"),
    path("api/admin/ops/audit", views.api_admin_ops_audit, name="api_admin_ops_audit"),
    path("api/admin/ops/errors", views.api_admin_ops_errors, name="api_admin_ops_errors"),
    path("api/events", views.api_events, name="api_events"),
    path("api/tools", views.api_tools, name="api_tools"),
    path("api/admin/events", views.api_admin_events, name="api_admin_events"),
    path("api/admin/events/<int:event_id>", views.api_admin_event_detail, name="api_admin_event_detail"),
    path("api/admin/tools", views.api_admin_tools, name="api_admin_tools"),
    path("api/admin/tools/<int:tool_id>", views.api_admin_tool_detail, name="api_admin_tool_detail"),
    path("api/banners", views.api_banners, name="api_banners"),
    path("api/admin/banners", views.api_admin_banners, name="api_admin_banners"),
    path("api/admin/banners/<int:banner_id>", views.api_admin_banner_detail, name="api_admin_banner_detail"),
]
